#!/bin/bash

ROOT=$(pwd)

if [[ -d ${ROOT}/datadir ]]
then
  echo $ROOT/datadir already exists. Nothing to do.
  exit
fi

mkdir -p ${ROOT}/datadir/mysql ${ROOT}/tmp
cp /usr/sbin/mysqld ${ROOT}

echo Bootstrap...

(echo 'use mysql;';
 cat /usr/share/mysql/mysql_system_tables.sql;
 cat /usr/share/mysql/mysql_system_tables_data.sql) |
${ROOT}/mysqld \
  --no-defaults --bootstrap \
  --loose-skip-innodb \
  --default-storage-engine=myisam \
  --datadir=${ROOT}/datadir \
  --tmpdir=${ROOT}/tmp/ \
  --lc-messages-dir=/usr/share/mysql \
  --character-sets-dir=/usr/share/mysql/charsets
