#!/bin/bash

ROOT=$(pwd)

echo ">>>>>> Connect: mysql -u root -S ${ROOT}/mysql.sock"
echo ">>>>>> Exit: press 'ctrl-\'"

${ROOT}/mysqld \
  --no-defaults \
  --datadir=${ROOT}/datadir \
  --tmpdir=${ROOT}/tmp/ \
  --lc-messages-dir=/usr/share/mysql \
  --character-sets-dir=/usr/share/mysql/charsets \
  --sock=${ROOT}/mysql.sock \
  --pid-file=${ROOT}/mysql.pid \
  --max_allowed_packet=32M \
  --innodb_log_file_size=128M \
  --innodb_buffer_pool_size=2G \
  --innodb_file_per_table \
  --skip-networking
